# Generated by Django 2.0.6 on 2018-07-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storedb',
            fields=[
                ('product', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('images', models.ImageField(upload_to='files')),
            ],
        ),
    ]
