# Generated by Django 2.0.6 on 2018-07-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('product', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
